services:
  app:
    image: danielhuisman/traefik-certificate-extractor
    container_name: ${ALIAS}
    restart: always
    volumes:
      - '/opt/dockers/traefik/letsencrypt:/app/data'
      - './certs:/app/certs'
      - './certs_flat:/app/certs_flat'
      - './extractor.py:/app/extractor.py'