version: "3.3"

services:
  ss-xray:
    image: "mazy/ss-xray:latest"
    container_name: "${ALIAS}"
    restart: unless-stopped
    networks:
      - default
      - proxy
    environment:
      - PASSWORD=${PASSWORD}
      - HOST=${HOST}
      - SERVER_ADDR=${SERVER_ADDR}
      - 'PLUGIN=xray-plugin'
      - 'PLUGIN_OPTS=server;path=/xray'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${ALIAS}rule=Host(`${HOST}`)"
      - "traefik.http.routers.${ALIAS}.entrypoints=https"
      - "traefik.http.routers.${ALIAS}.tls=true"
      - "traefik.http.routers.${ALIAS}.tls.certresolver=letsencrypt"
      - "traefik.http.services.${ALIAS}.loadbalancer.server.port=${PORT}"

networks:
    proxy:
      external: true