version: "3"

services:
  n8n:
    image: n8nio/n8n
    container_name: ${ALIAS}
    restart: always    
    ports:
      - ${PORT}:5678
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
      - N8N_HOST=${HOST}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_HIRING_BANNER_ENABLED=false
      - NODE_ENV=production
      - WEBHOOK_URL=https://${HOST}
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=168
      - DB_SQLITE_VACUUM_ON_STARTUP=true
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/home/node/.n8n      
    labels:
      # Enable Traefik for this service
      - traefik.enable=true

      # Define HTTP router
      - traefik.http.routers.${ALIAS}-http.entrypoints=http
      - traefik.http.routers.${ALIAS}-http.rule=Host(`${HOST}`)

      # Define HTTPS router
      - traefik.http.routers.${ALIAS}.entrypoints=https
      - traefik.http.routers.${ALIAS}.rule=Host(`${HOST}`)
      - traefik.http.routers.${ALIAS}.tls=true
      - traefik.http.routers.${ALIAS}.tls.certresolver=letsencrypt
      - traefik.http.routers.${ALIAS}.middlewares=${ALIAS}-to-https,${ALIAS}-headers # middlewares to load
      
      # Define the service to use for load balancing
      #- traefik.http.services.${ALIAS}.loadbalancer.server.port=0000

      # Redirect HTTP to HTTPS middleware
      - traefik.http.middlewares.${ALIAS}-to-https.redirectscheme.scheme=https

      # Security headers middleware
      - traefik.http.routers.${ALIAS}.middlewares=${ALIAS}-headers

      # Security headers middleware - Security headers configuration
      - traefik.http.middlewares.${ALIAS}-headers.headers.browserXSSFilter=true
      - traefik.http.middlewares.${ALIAS}-headers.headers.contentTypeNosniff=true
      - traefik.http.middlewares.${ALIAS}-headers.headers.frameDeny=true
      - traefik.http.middlewares.${ALIAS}-headers.headers.referrerPolicy=no-referrer
      - traefik.http.middlewares.${ALIAS}-headers.headers.customFrameOptionsValue=SAMEORIGIN

      # Security headers middleware - Strict Transport Security (HSTS) configuration
      - traefik.http.middlewares.${ALIAS}-headers.headers.stsSeconds=15552000
      - traefik.http.middlewares.${ALIAS}-headers.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.${ALIAS}-headers.headers.stsPreload=true
      - traefik.http.middlewares.${ALIAS}-headers.headers.forceSTSHeader=true

networks:
  proxy:
    external: true