version: '3'
services:
  phabricator:
    image: 'bitnami/phabricator:latest'
    user: root
    container_name: phabricator-app
    volumes:
       - ./data/app:/bitnami/phabricator
       - ./data/app-log:/opt/bitnami/phabricator/var/log
    expose:
       - 8080
       - 8443
    environment:
       - ALLOW_EMPTY_PASSWORD=no
       - PHABRICATOR_DATABASE_ADMIN_PASSWORD=${MARIADB_ROOT_PASSWORD}
       - PHABRICATOR_DATABASE_HOST=${PHABRICATOR_DATABASE_HOST}
       - PHABRICATOR_EMAIL=${PHABRICATOR_EMAIL}
       - PHABRICATOR_USERNAME=${PHABRICATOR_USERNAME}
       - PHABRICATOR_PASSWORD=${PHABRICATOR_PASSWORD}
       - PHABRICATOR_FIRSTNAME=${PHABRICATOR_FIRSTNAME}
       - PHABRICATOR_LASTNAME=${PHABRICATOR_LASTNAME}
       - PHABRICATOR_SMTP_HOST=${PHABRICATOR_SMTP_HOST}
       - PHABRICATOR_SMTP_PORT=${PHABRICATOR_SMTP_PORT}
       - PHABRICATOR_SMTP_USER=${PHABRICATOR_SMTP_USER}
       - PHABRICATOR_SMTP_PASSWORD=${PHABRICATOR_SMTP_PASSWORD}
       - PHABRICATOR_SMTP_PROTOCOL=${PHABRICATOR_SMTP_PROTOCOL}

    links:
      - mariadb
    networks:
      - private
      - proxy
    labels:
      - traefik.http.routers.${ALIAS}.middlewares=${ALIAS}Headers
      - traefik.http.middlewares.${ALIAS}Headers.headers.browserXSSFilter=true
      - traefik.http.middlewares.${ALIAS}Headers.headers.contentTypeNosniff=true
      - traefik.http.middlewares.${ALIAS}Headers.headers.frameDeny=true
      - traefik.http.middlewares.${ALIAS}Headers.headers.referrerPolicy=no-referrer
      - traefik.http.middlewares.${ALIAS}Headers.headers.customFrameOptionsValue=SAMEORIGIN
      - traefik.http.middlewares.${ALIAS}Headers.headers.SSLHost=${HOST}
      - traefik.http.middlewares.${ALIAS}Headers.headers.SSLRedirect=true
      - traefik.http.middlewares.${ALIAS}Headers.headers.stsSeconds=15552000
      - traefik.http.middlewares.${ALIAS}Headers.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.${ALIAS}Headers.headers.stsPreload=true
      - traefik.http.middlewares.${ALIAS}Headers.headers.forceSTSHeader=true
      #tls
      - traefik.http.routers.${ALIAS}.rule=Host(`${HOST}`)
      - traefik.http.routers.${ALIAS}.tls=true
      - traefik.http.routers.${ALIAS}.tls.certresolver=letsencrypt

  mariadb:
    image: bitnami/mariadb:latest
    user: root
    container_name: phabricator-db
    volumes:
       - ./data/db:/bitnami/mariadb/data
    ports:
      - 3306:3306
    networks:
      - private
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_SQL_MODE=STRICT_ALL_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
      - MARIADB_EXTRA_FLAGS=--local-infile=0 --max-allowed-packet=96M --innodb-buffer-pool-size=256MB

networks:
  # Change if you're using another network
  proxy:
    external: true
  private:
    driver: bridge
    internal: true