version: '3.7'

services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config/traefik.yml:/traefik.yml"
      - "./letsencrypt/acme.json:/acme.json"
      - "./logs:/logs"

  logrotate:
    container_name: ${ALIAS}-logrotate # Remove if using multiple instances
    image: vegardit/traefik-logrotate:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # required to send USR1 signal to Traefik after log rotation
      - "./logs:/logs" # folder containing access.log file
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      # all environment variables are optional and show the default values:
      LOGROTATE_LOGS: "/logs/*.log" # log files to rotate, directory must match volume mount
      LOGROTATE_TRIGGER_INTERVAL: daily  # rotate daily, must be one of: daily, weekly, monthly, yearly
      LOGROTATE_TRIGGER_SIZE: 50M        # rotate if log file size reaches 50MB
      LOGROTATE_MAX_BACKUPS: 14          # keep 14 backup copies per rotated log file
      LOGROTATE_START_INDEX: 1           # first rotated file is called access.1.log
      CRON_SCHEDULE: "* * * * *"
      CRON_LOG_LEVEL: 8                  # see https://unix.stackexchange.com/a/414010/378036
      # command to determine the id of the container running Traefik:
      TRAEFIK_CONTAINER_ID_COMMAND: docker ps --quiet --filter ancestor=traefik