services:
  traefik:
    image: traefik:latest
    container_name: ${ALIAS}
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket for dynamic configuration
      - ./config/traefik.yml:/traefik.yml          # Mount Traefik configuration file
      - ./letsencrypt/acme.json:/acme.json         # Mount Acme.json for Let's Encrypt certificates
      - ./logs:/logs                               # Mount logs directory for Traefik logs

  logrotate:
    image: vegardit/traefik-logrotate:latest
    container_name: ${ALIAS}-logrotate
    restart: always
    environment:
      TZ: ${TZ}                          # Set the timezone
      LOGROTATE_LOGS: "/logs/*.log"      # Log files to rotate (directory must match volume mount)
      LOGROTATE_TRIGGER_INTERVAL: daily  # Rotate daily (options: daily, weekly, monthly, yearly)
      LOGROTATE_TRIGGER_SIZE: 50M        # Rotate if log file size reaches 50MB
      LOGROTATE_MAX_BACKUPS: 14          # Keep 14 backup copies per rotated log file
      LOGROTATE_START_INDEX: 1           # First rotated file is called access.1.log
      CRON_SCHEDULE: "* * * * *"         # Cron schedule for log rotation
      CRON_LOG_LEVEL: 8                  # Log level for cron output
      TRAEFIK_CONTAINER_ID_COMMAND: docker ps --quiet --filter ancestor=traefik  # Command to determine Traefik container ID
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket to send USR1 signal to Traefik after log rotation
      - ./logs:/logs                               # Mount logs directory for log rotation