version: '3.7'

services:
  traefik:
    container_name: ${ALIAS} # Remove if using multiple instances
    networks:
      - proxy # Change if you're using another network
    labels:
      # Traefik configuration for the dashboard
      # Remove the labels section if the dashboard is disabled
      - "traefik.http.routers.${ALIAS}-http.rule=Host(`${HOST}`)"
      - "traefik.http.routers.${ALIAS}-http.service=api@internal"
      - "traefik.http.routers.${ALIAS}-http.entrypoints=http"
      - "traefik.http.routers.${ALIAS}-http.middlewares=redirect"

      - "traefik.http.routers.${ALIAS}-https.rule=Host(`${HOST}`)"
      - "traefik.http.routers.${ALIAS}-https.service=api@internal"
      - "traefik.http.routers.${ALIAS}-https.entrypoints=https"
      - "traefik.http.routers.${ALIAS}-https.tls=true"
      - "traefik.http.routers.${ALIAS}-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.${ALIAS}-https.middlewares=auth"

      - "traefik.http.middlewares.auth.basicauth.users=${LOGIN}:${PASSWORD}"

      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=1073741824"
      - "traefik.http.middlewares.autodetect.contenttype.autodetect=false"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
networks:
  # Change if you're using another network
  proxy:
    external: true
