version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: ${ALIAS}-mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/mysql
      - ./conf/mysql/override.cnf:/etc/mysql/conf.d/override.cnf     
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    networks:
      - private

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    networks:
      - private

  nextcloud:
    image: nextcloud:stable
    container_name: ${ALIAS}-nextcloud
    restart: unless-stopped
    volumes:
      - ./data/nextcloud:/var/www/html
      - ./conf/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    depends_on:
      - db
      - redis
    networks:
      - private
      - proxy
    ports:
      - "8081:80"
    labels:
      - traefik.http.routers.${ALIAS}.middlewares=${ALIAS}Headers
      - traefik.http.middlewares.${ALIAS}Headers.headers.browserXSSFilter=true
      - traefik.http.middlewares.${ALIAS}Headers.headers.contentTypeNosniff=true
      - traefik.http.middlewares.${ALIAS}Headers.headers.frameDeny=true
      - traefik.http.middlewares.${ALIAS}Headers.headers.referrerPolicy=no-referrer
      - traefik.http.middlewares.${ALIAS}Headers.headers.customFrameOptionsValue=SAMEORIGIN
      - traefik.http.middlewares.${ALIAS}Headers.headers.SSLHost=${HOST}
      - traefik.http.middlewares.${ALIAS}Headers.headers.SSLRedirect=true
      - traefik.http.middlewares.${ALIAS}Headers.headers.stsSeconds=15552000
      - traefik.http.middlewares.${ALIAS}Headers.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.${ALIAS}Headers.headers.stsPreload=true
      - traefik.http.middlewares.${ALIAS}Headers.headers.forceSTSHeader=true
      - traefik.http.middlewares.${ALIAS}Headers.headers.contentSecurityPolicy=font-src https://fonts.googleapis.com https://fonts.gstatic.com data:;      
      - traefik.http.routers.${ALIAS}.rule=Host(`${HOST}`)
      - traefik.http.routers.${ALIAS}.tls=true
      - traefik.http.routers.${ALIAS}.tls.certresolver=letsencrypt

  cron:
    image: nextcloud
    container_name: ${ALIAS}-cron
    restart: always
    volumes:
      - ./data/nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      - private
  
networks:
  proxy:
    external: true
  private:
    driver: bridge
    internal: true