version: '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${ALIAS}--phpmyadmin
    restart: "no"
    networks:
      - private
      - proxy
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
        PMA_HOST: db
        PMA_ABSOLUTE_URI: https://${PHPMYADMIN_HOST}/
    labels:
      - traefik.http.routers.${ALIAS}-phpmyadmin.rule=Host(`${PHPMYADMIN_HOST}`)
      - traefik.http.routers.${ALIAS}-phpmyadmin.tls=true
      - traefik.http.routers.${ALIAS}-phpmyadmin.tls.certresolver=letsencrypt
  db:
    image: mariadb:10-focal
    container_name: ${ALIAS}--mariadb
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - private
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    volumes:
      - ./data/mariadb:/var/lib/mysql

  strapi:
    image: strapi/strapi
    container_name: ${ALIAS}--strapi
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=${MYSQL_DATABASE}
      - DATABASE_USERNAME=${MYSQL_USER}
      - DATABASE_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${APP_PORT}:1337
    volumes:
      - ./data/strapi:/srv/app
    depends_on:
      - db
    networks:
      - private
      - proxy
    restart: unless-stopped
    labels:
      - traefik.http.routers.${ALIAS}.rule=Host(`${APP_HOST}`)
      - traefik.http.routers.${ALIAS}.tls=true
      - traefik.http.routers.${ALIAS}.tls.certresolver=letsencrypt
      - traefik.http.services.${ALIAS}.loadbalancer.server.port=1337
      
networks:
  # Traefik network
  proxy:
    external: true
  # Local network
  private:
    driver: bridge
    internal: true