version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: ${ALIAS}-mongo
    hostname: pritunldb
    restart: unless-stopped
    networks:
      - private
    volumes:
      - ./data/db:/data/db

  pritunl:
    image: goofball222/pritunl:latest
    container_name: ${ALIAS}-pritunl
    hostname: pritunl
    restart: unless-stopped
    depends_on:
        - mongo
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      - private
      - proxy
    links:
      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 1194:1194
      - 1194:1194/udp
      - 1195:1195/udp
    environment:
      - TZ=UTC
      - REVERSE_PROXY=true
      - WIREGUARD=false
    labels:
      - traefik.http.routers.${ALIAS}.rule=Host(`${HOST}`)
      - traefik.http.routers.${ALIAS}.tls=true
      - traefik.http.routers.${ALIAS}.tls.certresolver=lets-encrypt
      - traefik.http.services.${ALIAS}.loadbalancer.server.port=9700
      
networks:
  proxy:
    external:
      name: web
  private:
    driver: bridge
    internal: true
