shadowsocks:
  image: shadowsocks/shadowsocks-libev:edge
  container_name: ${ALIAS}
  ports:
    - "8388:8388/tcp"
    - "8388:8388/udp"
  environment:
    - METHOD=aes-256-gcm
    - PASSWORD=${PASSWORD}
  restart: always