version: "3"
services:
  netdata:
    image: netdata/netdata:latest
    container_name: ${ALIAS}-netdata
    restart: unless-stopped
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    networks:
      - proxy
    volumes:
      #- ./data/config/netdata.conf:/etc/netdata/netdata.conf
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    labels:
      # Enable Traefik for this service
      - traefik.enable=true

      # Define HTTP router
      - traefik.http.routers.${ALIAS}-http.entrypoints=http
      - traefik.http.routers.${ALIAS}-http.rule=Host(`${HOST}`)

      # Define HTTPS router
      - traefik.http.routers.${ALIAS}.entrypoints=https
      - traefik.http.routers.${ALIAS}.rule=Host(`${HOST}`)
      - traefik.http.routers.${ALIAS}.tls=true
      - traefik.http.routers.${ALIAS}.tls.certresolver=letsencrypt
      - traefik.http.routers.${ALIAS}.middlewares=${ALIAS}-to-https,${ALIAS}-headers # middlewares to load
      
      # Define the service to use for load balancing
      #- traefik.http.services.${ALIAS}.loadbalancer.server.port=0000

      # Redirect HTTP to HTTPS middleware
      - traefik.http.middlewares.${ALIAS}-to-https.redirectscheme.scheme=https

      # Security headers middleware
      - traefik.http.routers.${ALIAS}.middlewares=${ALIAS}-headers

      # Security headers middleware - Security headers configuration
      - traefik.http.middlewares.${ALIAS}-headers.headers.browserXSSFilter=true
      - traefik.http.middlewares.${ALIAS}-headers.headers.contentTypeNosniff=true
      - traefik.http.middlewares.${ALIAS}-headers.headers.frameDeny=true
      - traefik.http.middlewares.${ALIAS}-headers.headers.referrerPolicy=no-referrer
      - traefik.http.middlewares.${ALIAS}-headers.headers.customFrameOptionsValue=SAMEORIGIN

      # Security headers middleware - Strict Transport Security (HSTS) configuration
      - traefik.http.middlewares.${ALIAS}-headers.headers.stsSeconds=15552000
      - traefik.http.middlewares.${ALIAS}-headers.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.${ALIAS}-headers.headers.stsPreload=true
      - traefik.http.middlewares.${ALIAS}-headers.headers.forceSTSHeader=true  

networks:
  proxy:
    external: true