version: '3'
services:
  postgres:
    image: postgres:10.5
    container_name: ${ALIAS}-db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    #ports:
    #  - 5432:5432
    networks:
      - private   
  redis:
    image: redis:latest
    container_name: ${ALIAS}-redis
    restart: always
    networks:
      - private    
  cgwire:
    restart: always
    container_name: ${ALIAS}-app
    env_file:
      - .env
    image: kitsu--${KITSU_VERSION}_zou--${ZOU_VERSION}
    volumes:
      - ./data/thumbnails:/opt/zou/thumbnails
      - ./data/zou:/opt/zou/zou
      - ./data/previews:/opt/zou/previews
      #- ../wasabi/.kitsu/previews:/opt/zou/previews
    ports:
      - "${HTTP_PORT}:80"
    depends_on:
      - postgres
      - redis
    networks:
      - private
      - proxy
    labels:
      - traefik.http.routers.${ALIAS}.middlewares=${ALIAS}Headers
      - traefik.http.middlewares.${ALIAS}Headers.headers.browserXSSFilter=true
      - traefik.http.middlewares.${ALIAS}Headers.headers.contentTypeNosniff=true
      - traefik.http.middlewares.${ALIAS}Headers.headers.frameDeny=true
      - traefik.http.middlewares.${ALIAS}Headers.headers.referrerPolicy=no-referrer
      - traefik.http.middlewares.${ALIAS}Headers.headers.customFrameOptionsValue=SAMEORIGIN
      - traefik.http.middlewares.${ALIAS}Headers.headers.SSLHost=${HOST}
      - traefik.http.middlewares.${ALIAS}Headers.headers.SSLRedirect=true
      - traefik.http.middlewares.${ALIAS}Headers.headers.stsSeconds=15552000
      - traefik.http.middlewares.${ALIAS}Headers.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.${ALIAS}Headers.headers.stsPreload=true
      - traefik.http.middlewares.${ALIAS}Headers.headers.forceSTSHeader=true
      - traefik.http.middlewares.${ALIAS}Headers.headers.contentSecurityPolicy=font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com data:;
      #tls
      - traefik.http.routers.${ALIAS}.rule=Host(`${HOST}`)
      - traefik.http.routers.${ALIAS}.tls=true
      - traefik.http.routers.${ALIAS}.tls.certresolver=letsencrypt

networks:
  # Change if you're using another network
  proxy:
    external: true
  private:
    driver: bridge
    internal: true