version: '3.7'

services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config/traefik.yml:/traefik.yml"
      - "./letsencrypt/acme.json:/acme.json"
      - "./logs:/logs"

