version: '3.3'
services:
    x-ui:
        networks: 
          - proxy
        volumes:
            - '$PWD/db/:/etc/x-ui/'
            - '$PWD/cert/:/root/cert/'
        container_name: ${ALIAS}
        restart: unless-stopped
        image: ${ALIAS}-image
        ports:
          - "4434:54321"
        labels:
          - "traefik.http.routers.${ALIAS}.rule=Host(`${HOST}`)"
          - "traefik.http.routers.${ALIAS}.tls=true"
          - "traefik.http.routers.${ALIAS}.tls.certresolver=letsencrypt"

networks:
    proxy:
        external: true